<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_ke halaman login</name>
   <tag></tag>
   <elementGuidId>e50183d5-66f1-4261-9869-df7fbcba7795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonGoInTrack</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='buttonGoInTrack']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61c0a602-f130-4b9a-b239-64024861d849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGoInTrack</value>
      <webElementGuid>e9d187a7-aa14-4f49-946e-91ac1085f604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>230ebc4d-9c59-4b92-92cc-254b483ce0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silahkan
                                        Masuk</value>
      <webElementGuid>0f8d31e3-2c1f-4322-9d54-7d059237659b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonGoInTrack&quot;)</value>
      <webElementGuid>756fcc15-7d04-4b9d-8d44-078a7d5c1512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buttonGoInTrack']</value>
      <webElementGuid>e6d8dd3e-c8db-4ec8-83d7-a0ec541edb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Silahkan
                                        Masuk')]</value>
      <webElementGuid>0233b877-c77e-434e-bbc6-1bd4d24480f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About CODING.ID'])[1]/preceding::a[1]</value>
      <webElementGuid>772cb43b-9791-41d5-ae73-ea682a765dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Map'])[1]/preceding::a[1]</value>
      <webElementGuid>bac15a5a-a802-40b0-8817-3a9c9df17383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/login')])[5]</value>
      <webElementGuid>dc72666f-315a-4271-a694-631f6d488b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/a</value>
      <webElementGuid>c491346d-30a1-41c8-8bab-42290cfe2285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buttonGoInTrack' and @href = '/login' and (text() = 'Silahkan
                                        Masuk' or . = 'Silahkan
                                        Masuk')]</value>
      <webElementGuid>d3d844da-34f0-4c15-b8fa-41c1590d1f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
